# fly.toml app configuration file generated for white-snowflake-1092 on 2026-01-11T12:53:51+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'white-snowflake-1092'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
